config/routes.rb
Rails.application.routes.draw do
  
  root :to => 'landing#show'

  get "landing" => "landing#show"

  devise_for :users
  resources :users, only: [:show]
  resources :relationships, only: [:create, :destroy]  

  resources :users do
    member do
      get :following, :followers
    end
  end

  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags

  resources :favorite_tweets, only: [:create, :destroy]

  get "tweets" => "tweets#index"
  get "tweets/new" => "tweets#new"
  get "tweets/:id" => "tweets#show"
  post "tweets/create" => "tweets#create"
  post "tweets/destroy" => "tweets#destroy"

  get "searches" => "searches#show_result"
  get "searches/mentions" => "searches#search_mention"
  get "searches/hashtags" => "searches#search_hashtag"
  get "searches/musics" => "searches#search_music"
  get "searches/places" => "searches#search_place"

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

	def search_mention
		mentions = User.where("username LIKE ?", "%#{params[:q]}%")
    	render json: mentions
	end

	def search_hashtag
		hashtags = SimpleHashtagHashtag.where("name LIKE ?", "%#{params[:q]}%")
		render json: hashtags
	end

	def search_music
		musics = Music.where("name LIKE ?", "%#{params[:q]}%")
		render json: musics
	end

	def search_place
		places = Place.where("name LIKE ?", "%#{params[:q]}%")
		render json: places
	end

	def show_result
		@music = Music.search(params[:search_music])
		@place = Place.search(params[:search_place])

		@tweets_result = Tweet.search(@music.id, @place.id)
		@user = User.find(current_user.id)

		if @tweets_result.count == 0
			flash[:notice] = "Il n'y aucun résultat correspondant à votre recherche"
		end
	end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/show_result.html.erb
<div class="row">
	<div class="col-md-3 leftSide">
		<div class="avatar">
		<%= image_tag @user.avatar.url(:thumb) %>
		</div>
		<h2><%= @user.first_name %> <%= @user.last_name %></h2>
		<h2>@<%= @user.username %></h2>
		<p>Nombre de following : </p>
		<div class="nb"><%= @user.following.count %></div>
		<p>Nombre de followers : </p>
		<div class="nb"><%= @user.followers.count %></div>
	</div>
	<div class="col-md-7 centerSide searches">	
				<div class="searchForm">
			<h3>Trouver les meilleurs éléments en temps réel</h3>
			<%= form_tag searches_path,  class: 'navbar-form', method: :get do  %>
			<div class="form-group">
				<%= text_field_tag :search_music, params[:search_music], class: 'form-control input-music', placeholder: 'Music' %>
				<%= text_field_tag :search_place, params[:search_place], class: 'form-control input-place', placeholder: 'Place' %>
			</div>
			<%= submit_tag 'Search', class: 'btn btn-default' %>
			<% end %>
		</div>
		<% @tweets_result .each do |tweet| %>
			<div class="well">
			<div class="media">
				<a class="pull-left" href="#">
					<div class="avatarSmall">
					<%= image_tag tweet.user.avatar.url(:small) %>
					</div>
				</a>
				<div class="media-body">
					<h4 class="media-heading"><%= "#{tweet.user.first_name} #{tweet.user.last_name}"%> <small><%= link_to( "@#{tweet.user.username} " , "/users/#{tweet.user.id} ")%></small> </h4>
					<p><%= content_hashtag_link(tweet.content) %></p>
					<ul class="list-inline list-unstyled">
						<li><span><i class="glyphicon glyphicon-calendar"></i> <%= link_to(time_ago_in_words(tweet.created_at), "/tweets/#{tweet.id} ") %></span></li>
						<% if current_user %>
						<li><span><i class="glyphicon glyphicon-star"></i> 
							<% unless current_user.favorite_tweets.exists?(id: tweet.id) %>
								<%= link_to 'Add to favorites', favorite_tweets_path(tweet_id: tweet), method: :post %>
							<% else -%>
								<%= link_to 'Remove from favorites', favorite_tweet_path(tweet), method: :delete %>
							<% end %>
						</span></li>
						<% end %>
						<li><span><i class="glyphicon glyphicon-music"></i> <%= tweet.music.name %></span></li>
						<li><span><i class="glyphicon glyphicon-globe"></i> <%= tweet.place.name %></span></li>
					</ul>
				</div>
			</div>
		</div>
		<% end %>
	</div>

	<div class="col-md-3">

	</div>	
</div>