config/routes.rb
Rails.application.routes.draw do
  
  root :to => 'landing#show'

  get "landing" => "landing#show"

  devise_for :users
  resources :users, only: [:show]
  resources :relationships, only: [:create, :destroy]  

  resources :users do
    member do
      get :following, :followers
    end
  end

  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags

  resources :favorite_tweets, only: [:create, :destroy]

  get "tweets" => "tweets#index"
  get "tweets/new" => "tweets#new"
  get "tweets/:id" => "tweets#show"
  post "tweets/create" => "tweets#create"
  post "tweets/destroy" => "tweets#destroy"

  get "searches" => "searches#show_result"
  get "searches/mentions" => "searches#search_mention"
  get "searches/hashtags" => "searches#search_hashtag"
  get "searches/musics" => "searches#search_music"
  get "searches/places" => "searches#search_place"

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :favorited, polymorphic: true
  belongs_to :user
end

app/models/music.rb
class Music < ActiveRecord::Base
	has_many :tweet

	# Search by music
	def self.search(query)
		where("name like ?", "%#{query}%").first_or_create
	end
end

app/models/place.rb
class Place < ActiveRecord::Base
	has_many :tweet

	def self.search(query)
	  where("name like ?", "%#{query}%").first_or_create
	end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true  	
end

app/models/simple_hashtag_hashtag.rb
class SimpleHashtagHashtag < ActiveRecord::Base

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	include SimpleHashtag::Hashtaggable
	hashtaggable_attribute :content

	has_many :favorites, as: :favorited

	belongs_to :place
	belongs_to :music
	belongs_to :user

	validates :content,  presence: true, :length => { :maximum => 140}
	validates :user_id,  presence: true

	default_scope { order('tweets.created_at DESC')}


	def self.search(music, place)
		m = "%#{music}%"
		p = "%#{place}%"
		where("music_id like ? AND place_id like ?", m, p).order(created_at: :desc)
	end

	def self.feed(current_user)
		first = Tweet.where(user_id: Relationship.select(:followed_id).where(follower_id: "#{current_user}")).order(created_at: :asc)
		second = Tweet.where(user_id: "#{current_user}").order(created_at: :asc)
		return (first + second).sort{|a,b| a.created_at <=> b.created_at }.reverse

	end 

	def self.feedByUser(user_id)
		Tweet.where(user_id: "#{user_id}").order(created_at: :desc)
	end 


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, 
  :validatable, :authentication_keys => [:login]

  #Paperclip
  has_attached_file :avatar, :styles => { :medium => "400x400#>", :thumb => "200x200#", :small => "60x60#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  has_many :tweets

  validates :username,
  :uniqueness => {
    :case_sensitive => false
  }
  # Follow
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower



  has_many :retweet
  has_many :tweet, :through => :retweet

  has_many :favorites
  has_many :favorite_tweets, through: :favorites, source: :favorited, source_type: 'Tweet'                           

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

	def self.find_first_by_auth_conditions(warden_conditions)
	  conditions = warden_conditions.dup
	  if login = conditions.delete(:login)
	    where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
	  else
	    where(conditions).first
	  end
	end

  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
  
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController

  def index
    @hashtags = SimpleHashtag::Hashtag.all
  end

  def show
    @hashtag = SimpleHashtag::Hashtag.find_by_name(params[:hashtag])
    @hashtagged = @hashtag.hashtaggables if @hashtag
    if user_signed_in?
    	@user = User.find(current_user.id)
    end
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
	def show
		if current_user 
			redirect_to tweets_path
		end
	end	
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

	def search_mention
		mentions = User.where("username LIKE ?", "%#{params[:q]}%")
    	render json: mentions
	end

	def search_hashtag
		hashtags = SimpleHashtagHashtag.where("name LIKE ?", "%#{params[:q]}%")
		render json: hashtags
	end

	def search_music
		musics = Music.where("name LIKE ?", "%#{params[:q]}%")
		render json: musics
	end

	def search_place
		places = Place.where("name LIKE ?", "%#{params[:q]}%")
		render json: places
	end

	def show_result
		@music = Music.search(params[:search_music])
		@place = Place.search(params[:search_place])

		@tweets_result = Tweet.search(@music.id, @place.id)
		@user = User.find(current_user.id)

		if @tweets_result.count == 0
			flash[:notice] = "Il n'y aucun résultat correspondant à votre recherche"
		end
	end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    if user_signed_in?
      @tweets = Tweet.feed(current_user.id)
      @user = User.find(current_user.id)
    else 
       @tweets = Tweet.all
    end
  end

  def new
    @new_tweet = Tweet.new
    @user = User.find(current_user.id)
  end

def show
    @tweet = Tweet.find(params[:id])
    if user_signed_in?
    @user = User.find(current_user.id)
    end
  end

  def create
    if (params[:tweet][:place_id] == "" || params[:tweet][:place_id] == "") 
       flash[:notice] = "Veuillez sélectionner un genre de musique et/ou un lieux"
       redirect_to(tweets_new_path)
    else
      tweet = Tweet.create(
        user_id: current_user.id,
        content: params[:tweet][:content], 
        place_id: params[:tweet][:place_id], 
        music_id: params[:tweet][:music_id]
      )
       redirect_to(tweets_path)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user, only: [:index, :edit, :update, :destroy, :following, :followers]
  
  def show
    @user = User.find(params[:id])
    @tweets = Tweet.feedByUser(params[:id])
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
  def linkify_hashtags(hashtaggable_content)
    regex = SimpleHashtag::Hashtag::HASHTAG_REGEX
    hashtagged_content = hashtaggable_content.to_s.gsub(regex) do
      link_to($&, hashtag_path($2), {class: :hashtag})
    end
    hashtagged_content.html_safe
  end

  def render_hashtaggable(hashtaggable)
    klass        = hashtaggable.class.to_s.underscore
    view_dirname = klass.pluralize
    partial      = klass
    render "#{view_dirname}/#{partial}", {klass.to_sym => hashtaggable}
  end
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <div class="btnHome"><%= link_to image_tag("home_grey.svg"), landing_path, class: 'navbar-brand' %></div>
        </div>

        <div id="navbar" class="navbar-collapse collapse ">
          <ul class="nav navbar-nav navbar">
          <div class="btnIcone"><%= link_to image_tag("icone-metronome.svg"), tweets_path%></div>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="btn connection"><%= link_to "S'inscrire", new_user_registration_path %></li>
            <li class="btn connection"><%= link_to "Se connecter", new_user_session_path %></li>
          </ul>

          <form class="navbar-form navbar-right">
            <input type="text" class="form-control input-hashtags-mentions" placeholder="Rechercher...">
          </form>

        </div><!--/.nav-collapse -->




      </div>
    </nav>

app/views/layouts/_header_logged.html.erb
<!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <div class="btnHome"><%= link_to image_tag("home_grey.svg"), landing_path, class: 'navbar-brand' %></div>          
        </div>

        <div id="navbar" class="navbar-collapse collapse ">
          <ul class="nav navbar-nav">
            <div class="btnIcone"><%= link_to image_tag("icone-metronome.svg"), tweets_path%></div>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle btnHeadMenu" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.username %><span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Profil", "#{users_path}/#{current_user.id}" %></li>
                <li><%= link_to "Actualité", tweets_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Editer son profil", edit_user_registration_path %></li>
                <li><%= link_to "Déconnexion", destroy_user_session_path, :method => :delete %></li>
              </ul>
              <li class="btn connection"><%= image_tag "plume.svg" %><%= link_to "Poster", tweets_new_path %></li>
            </li>
          </ul>

          <form class="navbar-form navbar-right">
            <input type="text" class="form-control input-hashtags-mentions" placeholder="Rechercher...">
          </form>

        </div><!--/.nav-collapse -->



      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>Twittby</title>
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>
  </head>

  <body>
  
  	<%= 
  	if current_user
		render "layouts/header_logged"
	else
		render "layouts/header"
	end 
	%>

	<div class="container">
		<% if notice %>
	 		<p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
	  		<p class="alert alert-danger"><%= alert %></p>
		<% end %>
		<%=yield %>
</div><!-- /.container -->
</body>
</html>